version: "3.8"

services:
  backend:
    build:
      context: ./backend
    image: social-media-scraper-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/social_media

  frontend:
    build:
      context: ./frontend
    image: social-media-scraper-frontends
    ports:
      - "3000:80"

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-capped-collection.js:/docker-entrypoint-initdb.d/init-capped-collection.js

volumes:
  mongodb_data:
