version: "3.8"

services:
  backend:
    build:
      context: ./backend
      args:
        - BUILD_NUMBER:${BUILD_NUMBER}
    image: social-media-scraper-backend:${BUILD_NUMBER}
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/social_media
    networks:
      - jenkins_env

  frontend:
    build:
      context: ./frontend
    image: social-media-scraper-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:5000
    networks:
      - jenkins_env

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-capped-collection.js:/docker-entrypoint-initdb.d/init-capped-collection.js
    networks:
      - jenkins_env

networks:
  jenkins_env:
    
volumes:
  mongodb_data:
